/**
 * Shipping Rate Seed Data
 * Zones A, B, C, D with weight ranges and multipliers
 */

module.exports = [
  // ────────────────────────
  // ⭐ ZONE A — 0–5 km
  // ────────────────────────
  {
    shippingType: 'standard',
    zone: 'A',
    weightMin: 0,
    weightMax: 1,
    baseFee: 20,
    perKgFee: 0,
    weightAddOn: 0,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },
  {
    shippingType: 'standard',
    zone: 'A',
    weightMin: 1,
    weightMax: 5,
    baseFee: 25,
    perKgFee: 0,
    weightAddOn: 10,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },
  {
    shippingType: 'standard',
    zone: 'A',
    weightMin: 5,
    weightMax: 10,
    baseFee: 30,
    perKgFee: 0,
    weightAddOn: 15,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },

  // ────────────────────────
  // ⭐ ZONE B — 5–10 km
  // ────────────────────────
  {
    shippingType: 'standard',
    zone: 'B',
    weightMin: 0,
    weightMax: 1,
    baseFee: 35,
    perKgFee: 0,
    weightAddOn: 0,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },
  {
    shippingType: 'standard',
    zone: 'B',
    weightMin: 1,
    weightMax: 5,
    baseFee: 40,
    perKgFee: 0,
    weightAddOn: 10,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },
  {
    shippingType: 'standard',
    zone: 'B',
    weightMin: 5,
    weightMax: 10,
    baseFee: 45,
    perKgFee: 0,
    weightAddOn: 15,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },

  // ────────────────────────
  // ⭐ ZONE C — 10–20 km
  // ────────────────────────
  {
    shippingType: 'standard',
    zone: 'C',
    weightMin: 0,
    weightMax: 1,
    baseFee: 50,
    perKgFee: 0,
    weightAddOn: 0,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },
  {
    shippingType: 'standard',
    zone: 'C',
    weightMin: 1,
    weightMax: 5,
    baseFee: 60,
    perKgFee: 0,
    weightAddOn: 10,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },
  {
    shippingType: 'standard',
    zone: 'C',
    weightMin: 5,
    weightMax: 10,
    baseFee: 70,
    perKgFee: 0,
    weightAddOn: 15,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },

  // ────────────────────────
  // ⭐ ZONE D — 20–35 km
  // ────────────────────────
  {
    shippingType: 'standard',
    zone: 'D',
    weightMin: 0,
    weightMax: 1,
    baseFee: 60,
    perKgFee: 0,
    weightAddOn: 0,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },
  {
    shippingType: 'standard',
    zone: 'D',
    weightMin: 1,
    weightMax: 5,
    baseFee: 70,
    perKgFee: 0,
    weightAddOn: 10,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },
  {
    shippingType: 'standard',
    zone: 'D',
    weightMin: 5,
    weightMax: 10,
    baseFee: 80,
    perKgFee: 0,
    weightAddOn: 15,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },

  // ────────────────────────
  // ⭐ ZONE E — 35–50 km
  // ────────────────────────
  {
    shippingType: 'standard',
    zone: 'E',
    weightMin: 0,
    weightMax: 1,
    baseFee: 80,
    perKgFee: 0,
    weightAddOn: 0,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },
  {
    shippingType: 'standard',
    zone: 'E',
    weightMin: 1,
    weightMax: 5,
    baseFee: 90,
    perKgFee: 0,
    weightAddOn: 10,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },
  {
    shippingType: 'standard',
    zone: 'E',
    weightMin: 5,
    weightMax: 10,
    baseFee: 100,
    perKgFee: 0,
    weightAddOn: 15,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },

  // ────────────────────────
  // ⭐ ZONE F — 50+ km
  // ────────────────────────
  {
    shippingType: 'standard',
    zone: 'F',
    weightMin: 0,
    weightMax: 1,
    baseFee: 100,
    perKgFee: 0,
    weightAddOn: 0,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },
  {
    shippingType: 'standard',
    zone: 'F',
    weightMin: 1,
    weightMax: 5,
    baseFee: 110,
    perKgFee: 0,
    weightAddOn: 10,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },
  {
    shippingType: 'standard',
    zone: 'F',
    weightMin: 5,
    weightMax: 10,
    baseFee: 120,
    perKgFee: 0,
    weightAddOn: 15,
    standardMultiplier: 1.0,
    sameDayMultiplier: 1.2,
    expressMultiplier: 1.4,
    fragileSurcharge: 5,
    weekendSurcharge: 10,
    nightSurcharge: 8,
    estimatedDays: '1-3 days',
    isActive: true,
  },
];

